### ISSUE TITLE
Incorrect variable names (chapter 5.3)

### ISSUE THREAD

**Issue by erykwalczak** [csgillespie/efficient#14]
Hi Colin,

I'm going through your book and I find it very enlightening.

I think that I found a mistake in naming variables:

In chapter 5.3 (Plain text formats) you assign the variables in the following way:

```
df_co2_dt = readr::read_csv("extdata/co2.csv")
df_co2_readr = data.table::fread("extdata/co2.csv")
```

It looks to me like the names are the inverse of what they should be.

I hope this helps,
Eryk

**Comment by csgillespie** [comment]
Thanks and good spot. 

I've checked the code and fortunately figure 5.1 is fine. I'll contact O'Reilly and update the online version.

**Comment by csgillespie** [comment]
Notified O'Reilly
