### ISSUE TITLE
data wb_ineq in section 6.4.2

### ISSUE THREAD

**Issue by ecosang** [csgillespie/efficient#16]
Hello,
in section 6.4.2, it looks like the dataset `wb_ineq` provided by `efficient` package does not have character types for all variables. Which is not consistent with the text. 

(FYI, in the text, all types of variables are character, so the `mean(wb_ineq$gini)` fails. BUt, it fails due to missing `na.rm=T`, not the type since the dataset `wb_ineq` in `efficient` package is already numerical data type for some columns.

I would like to suggest to modify the dataset or add line
`wb_ineq<-mutate_all(wb_ineq,funs(as.character))`.
The first method looks better though.
or did I understand in wrong way?

**Comment by csgillespie** [comment]
@Robinlovelace would you have a look at this? Thanks

**Comment by Robinlovelace** [comment]
Will do.

**Comment by Robinlovelace** [comment]
I tried modifying the dataset first but for some reason this led to errors like this: https://support.bioconductor.org/p/97344/ . Instead I've rewritten the relevant code so it doesn't make incorrect statements about `wb_ineq`. @ecosang I'd be grateful if you could have a look at the updated results and let me know if this is fixed from your perspective. Any further issues you find please let us know or put in another PR. Thanks!

**Comment by ecosang** [comment]
@Robinlovelace  Thanks. Though it is not a perfect solution, it looks like there is no problem in text and dataset both (I think).  Thank you for the response.
